version: "3"

services:
  app:
    image: laravel-www
    container_name: projeto_laravel
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
