version: "3"

services:
  app:
    image: laravel
    container_name: trabalho_01
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
