version: "3.5"
services:
  app:
    container_name: desafio
    image: unialfa-php
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_DISCOVER_CLIENT_HOST=false
    ports:
      - "8080:80"
    networks:
      - minha-rede

networks:
  minha-rede:
    name: minha-rede
    driver: bridge